# -*- coding: utf-8 -*-
"""JB_GTFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnCPRQHF-w5uk1dU5sNZMbYGXbuBl4M6

## 1. Imports e deteção de ambiente

Deteção automática do ambiente de execução: `jupyter` (Google Colab) ou `flask` (local/Render).  
Em ambiente flask, as credenciais são lidas via ficheiros secrets.
"""

import datetime
import json
import requests
import types
import socket
import os
import zipfile
import pandas as pd


try:
    from google.colab import userdata
    #! pip install clts_pcp pymysql "pymongo[srv]" --quiet
    #! pip install psycopg2
    import pymysql
    import clts_pcp as clts
    ENV = "jupyter"
except ImportError:
    # Ambiente flask
    import clts_pcp as clts
    ENV = "flask"

    # local:  ./secrets/
    # render: /etc/secrets/
    hostname_short = socket.gethostname()
    if hostname_short[:4] == "srv-":
        secrets_path = "/etc/secrets"
    else:
        secrets_path = "./secrets"
    userdata = types.SimpleNamespace()
    userdata.get = lambda key: open(f"{secrets_path}/{key}").read()
    

print("Ambiente detetado:", ENV)

"""## 2. Reconhecimento do contexto

Identifica o servidor, utilizador, script e configurações de execução.  
O `context` é usado em logs e no assunto do email de notificação.

**Credenciais necessárias nesta pipeline:**
```
JB-dblist.json          → lista de bases de dados destino
JB-mongodb.json         → credenciais MongoDB Atlas
configGMail_JB.json     → credenciais Gmail para envio de notificações
```
"""

# timestamp inicial
# usado para profiling ao longo da pipeline
tstart=clts.getts()

# Default configuration with alternatives documented
DEFAULT_PARAMS = {
    "verbose": True,           # alternatives: [True, False]
    "destination": "-*-",         # deprecated to use several alternatives: ['localhost', 'baze.cm-maia.pt', 'aiven'] - see below
    "send_mail": True,          # alternatives: [True, False]
    #"email_addresses": ["pedroccpimenta@gmail.com", 'ppimenta.umaia@gmail.com' ]  # array of email addresses - alternatives: ['ppimenta@umaia.pt', 'ppimenta@cm-maia.pt']
    "email_addresses": ["up202303784@g.uporto.pt" ]
    }

# get hostanme of the machine where the script is running
hostname = socket.gethostname()
# returns current IP address in plain text
ip = requests.get('https://api.ipify.org').text

print("Server name:", hostname, "Public IP Address:", ip)

if ENV == "jupyter":
    #!pip install ipynbname --quiet
    import ipynbname
    notebookname = requests.get("http://172.28.0.12:9000/api/sessions").json()[0]["name"]
    user = notebookname.split("_")[0]
    script = ipynbname.name()
    channel = notebookname.split("_")[1]
    datapath = "/content"
    verbose = DEFAULT_PARAMS['verbose']
    destination = DEFAULT_PARAMS['destination']
    send_mail = DEFAULT_PARAMS['send_mail']
    email_addresses = DEFAULT_PARAMS['email_addresses']
    clts.elapt[f"running colab notebook: {script}"] = clts.deltat(tstart)

else:
  # Flask local ou Render :  vars de ambiente
  user = os.environ.get("D5_USER", "JB")
  script = os.path.basename(__file__)
  channel = "GTFS"
  datapath = os.environ.get("D5_DATAPATH", ".")
  verbose = DEFAULT_PARAMS["verbose"]
  send_mail = DEFAULT_PARAMS["send_mail"]
  email_addresses = DEFAULT_PARAMS["email_addresses"]
  destination = DEFAULT_PARAMS["destination"]
  clts.elapt[f"script: {script}"] = clts.deltat(tstart)

# The overall format of context should be:
# server (ip) | user | channel | file.py | database destination (to be deprecated)
context= f'{hostname} ({ip}) | {user} | {channel} | {script} | {destination}'
clts.setcontext(context)

now = str(datetime.datetime.now())[0:19]
hoje = now[:10]

if verbose:
  print("context:", context)
  print("datapath:", datapath)

"""## 3. Recolha de dados (ZIP GTFS)

Extrai os ficheiros GTFS do ZIP e carrega as tabelas da Fase 1.  
O ZIP deve estar em `datapath` — no Colab, fazer upload manual para `/content/`.
"""

GTFS_URL = GTFS_URL = "https://opendata.porto.digital/dataset/15f22603-a216-492a-ab1c-40b1d8aa2f08/resource/f592c53a-e669-4cac-9e28-ab84b87e7f6b/download/horarios_gtfs_09_09_2024.zip"
zip_path = os.path.join(datapath, "metro_porto.zip")
gtfs_path = os.path.join(datapath, "gtfs_data")
output_path = os.path.join(datapath, "output")

os.makedirs(gtfs_path, exist_ok=True)
os.makedirs(output_path, exist_ok=True)

response = requests.get(GTFS_URL)
response.raise_for_status()

with open(zip_path, "wb") as f:
  f.write(response.content)

print("Status:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))
print("Tamanho:", len(response.content), "bytes")
print("Primeiros bytes:", response.content[:100])

# extract zip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(gtfs_path)

clts.elapt["Download and extracted GTFS Metro do Porto"] = clts.deltat(tstart)
print("ZIP extraído para:", gtfs_path)

"""## 4. Pré-processamento

Carrega as tabelas GTFS (Fase 1) e gera métricas básicas de validação.
"""

gtfs_folder = next(f for f in os.listdir(gtfs_path) if os.path.isdir(os.path.join(gtfs_path, f)))
# load GTFS tables

stops      = pd.read_csv(os.path.join(gtfs_path, gtfs_folder, "stops.txt"))
routes     = pd.read_csv(os.path.join(gtfs_path, gtfs_folder, "routes.txt"))
trips      = pd.read_csv(os.path.join(gtfs_path, gtfs_folder, "trips.txt"))
stop_times = pd.read_csv(os.path.join(gtfs_path, gtfs_folder, "stop_times.txt"))
shapes     = pd.read_csv(os.path.join(gtfs_path, gtfs_folder, "shapes.txt"))
calendar   = pd.read_csv(os.path.join(gtfs_path, gtfs_folder, "calendar.txt"))
agency     = pd.read_csv(os.path.join(gtfs_path, gtfs_folder, "agency.txt"))

print(stops.columns)
print(routes.columns)
print(trips.columns)
print(stop_times.columns)
print(shapes.columns)
print(calendar.columns)
print(agency.columns)



# simple validation
print("\nDataset sizes:")
print("Stops:", len(stops))
print("Routes:", len(routes))
print("Trips:", len(trips))
print("Stop Times:", len(stop_times))
print("Shapes:", len(shapes))
print("Calendar:", len(calendar))
print("Agency:", len(agency))



"""# 5. Conexão e Upsert na(s) base(s) de dados

Para cada tuplo (`user`, `base de dados`), deverá haver um ficheiro de credenciais do tipo:

```
{
	"manifesto":"text describing the credencials",
	"filename":"<redundant>",
	"dest_host":"conection url to the database",
	"username":"username",
	"password":"password",
	"database":"database",
	"port":12345678,
	"burl4api": "base url of the api exposing the data",
	"timeout":20,
	"dbms":"dmbs type"
}
```
"""

# The script have to be parametrized by 'User' (so the script could be portable between users)
# The script have to be parametrized by 'User' (so the script could be portable between users)

from pymongo import MongoClient
import psycopg2


clts.elapt[f"Starting database accesses:"] = clts.deltat(tstart)


gtfs_tables = [
    ("stops", stops, "stop_id"),
    ("routes", routes, "route_id"),
    ("trips", trips, "trip_id"),
    ("stop_times", stop_times, ["trip_id", "stop_sequence"]),
    ("shapes", shapes, ["shape_id", "shape_pt_sequence"]),
    ("calendar", calendar, "service_id"),
    ("agency", agency, "agency_id")
]

tstamp = clts.getts()

# Esta variável foi definida no início da execução desta notebook
# user = "pcp"  # Outras alternativas podem ser gmartins, mlbaltar, rmendes, ...
# dblist=json.loads(open(f"{user}-dblist.json")) # each user might use different destination databases
# This connection needs further parametrization, since the same user might want to use
# different databases for different pipelines / data sources
dblist=json.loads(userdata.get(f"{user}-dblist.json"))
print("Bases de dados de destino:", dblist)


for dbname in dblist:
    status = "nok"
    clts.elapt[f"Connecting to `{dbname}`"] = clts.deltat(tstart)

    try:
        dbcreds = json.loads(userdata.get(f'{user}-{dbname}.json'))

        raw = userdata.get(f"{user}-{dbname}.json")
        print(raw)

        if dbcreds['dbms'] == "mongodb":
            mongo_uri = f"mongodb+srv://{dbcreds['username']}:{dbcreds['password']}@{dbcreds['dest_host']}/{dbcreds['database']}"

            client = MongoClient(mongo_uri)
            db = client[dbcreds['database']]
            clts.elapt[f"... connected to `{dbname}`"] = clts.deltat(tstart)

            for (colname, df, key) in gtfs_tables:
                collection = db[colname]
                print(f"\nProcessing {colname}...")

                keys = key if isinstance(key, list) else [key]

                if len(keys) == 1:
                    existing_ids = {doc.get(keys[0]) for doc in collection.find({}, {keys[0]: 1})}
                else:
                    existing_ids = {tuple(doc.get(k) for k in keys) for doc in collection.find({}, {k: 1 for k in keys})}


                docs = []
                skipped = 0
                # build batch
                for _, row in df.iterrows():
                    row_key = row[keys[0]] if len(keys) == 1 else tuple(row[k] for k in keys)
                    if row_key not in existing_ids:
                        doc = row.to_dict()
                        doc["hostsource"] = hostname
                        doc["tstamp"] = tstamp
                        docs.append(doc)
                    else:
                      skipped += 1

                # insert all at once
                if docs:
                    collection.insert_many(docs)


                clts.elapt[f"... [{dbname}] {colname}: inserted {len(docs)}, skipped {skipped}"] = clts.deltat(tstart)

            status = "ok"

        elif dbcreds['dbms'] == "cratedb":
            conn = psycopg2.connect(
                host=dbcreds['dest_host'],
                port=dbcreds['port'],
                database=dbcreds['database'],
                user=dbcreds['username'],
                password=dbcreds['password']
            )

            # used to execute SQL queries on an SQLite database
            cursor = conn.cursor()
            cursor.execute("SET search_path TO doc")
            cursor.execute("SELECT current_schema()")
            print("schema atual:", cursor.fetchone())

            clts.elapt[f"... connected to `{dbname}` (CrateDB)"] = clts.deltat(tstart)
            from psycopg2.extras import execute_values

            for (tablename, df, key) in gtfs_tables:
                print(f"\nProcessing {tablename}...")

                new_rows = df.copy()
                new_rows["hostsource"] = hostname
                new_rows["tstamp"] = datetime.datetime.now()

                cols = list(new_rows.columns)
                columns_sql = ", ".join(cols)
                values = list(new_rows.itertuples(index=False, name=None))

                # Bulk insert with RETURNING 1 and fetch=True
                # 'RETURNING 1' simply returns the number '1' for every successful insert
                inserted_records = execute_values(
                    cursor,
                    f"INSERT INTO {tablename} ({columns_sql}) VALUES %s ON CONFLICT DO NOTHING RETURNING 1",
                    values,
                    fetch=True
                )
                conn.commit()

                # The length of the returned list is your exact, accurate insert count
                inserted = len(inserted_records) if inserted_records else 0
                skipped = len(new_rows) - inserted

                clts.elapt[f"... [{dbname}] {tablename}: inserted {inserted}, skipped {skipped}"] = clts.deltat(tstart)

            cursor.close()
            conn.close()
            status = "ok"

    except Exception as e:
        import traceback
        traceback.print_exc()
        print("Error:", e)
        clts.elapt[f"... error `{e}` ❌"] = clts.deltat(tstart)
        status = 'onerror'

    print("status:", status)
    print("Connection closing....")

"""# 6. Sending tasks summary by email

In order to send email (smtp / SSL @ gmail), a last credentials file is needed, in the form:

```
{
	"manifesto":"text describing the credencials.",

	"UserName":"username",
	"UserFrom":"email address",

	"UserPwd":"password"
}
```

Again, the filename of this file could be parametrized as <user>-<email service> or <user>-<email service>-<hostname> - to be discussed.

"""

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import smtplib, ssl

clts.elapt["Overall (before email):"]=clts.deltat(tstart)
hora=str(datetime.datetime.now())[11:13]
horaemail=['07', '17' ]

toem=clts.listtimes()

#if sendmail and (hora in horaemail):
if send_mail and email_addresses!=[]:
    try:
        credsgmail=json.loads(userdata.get('configGMail_JB.json') )

        assunto = f"{context}"
        message = MIMEMultipart("alternative")
        message["Subject"] = assunto

        message["From"]=credsgmail['UserFrom']
        message["To"]=", ".join(email_addresses)
        # message["Reply-To"]="ppimenta@ipmaia.pt"

        text = toem+"\nEsta é uma mensagem automática."

        html = "<html><body style=''font-family:Montserrat;''>"+toem+ "<hr color=orange>"
        html = html +"This message is an automated notification from "+ context +"</body></html>"

        # Turn these into plain/html MIMEText objects
        part1 = MIMEText(text, "plain")
        part2 = MIMEText(html, "html")

        # Add HTML/plain-text parts to MIMEMultipart message
        # The email client will try to render the last part first
        message.attach(part1)
        message.attach(part2)

        port = 465 # SSL

        # Create a secure SSL context
        ssl_context = ssl.create_default_context()

        with smtplib.SMTP_SSL("smtp.gmail.com", port, context=ssl_context) as server:
          server.login(credsgmail['UserName'], credsgmail['UserPwd'])
          sender_email = credsgmail['UserFrom']
          server.sendmail(sender_email, email_addresses, message.as_string())

        print ("Notificação enviada.")
        clts.elapt[f"After sending email"] = clts.deltat(tstart)        # add an entry to elapt dictionary
    except Exception  as e:
        print('A notificação não foi enviada:', e)
        clts.elapt[f"email not sent ({e})"] = clts.deltat(tstart)       # add an entry to elapt dictionary
    finally:
        pass



print(clts.listtimes())
